management:
  endpoints:
    web:
      exposure:
        include: "*"
jasypt:
  encryptor:
    bean: encryptorBean
--- #local
spring:
  application:
    name: admin
  profiles:
    active: local
  config:
    import: optional:configserver:https://dev-config.piece.run
  cloud:
    config:
      uri: http://dev.cconfig.piece.run

--- #dev
spring:
  application:
    name: admin
  profiles:
    active: local
  config:
    import: optional:configserver:https://dev-config.piece.run
  cloud:
    config:
      uri: http://dev.cconfig.piece.run